name: voice_text_app
description: "Voice to Text and Text to Voice App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2

flutter:
  uses-material-design: true
  assets:
    - icon.png
